use_frameworks!
platform :ios, '11.0'

target 'SVLatexView_Example' do
  pod 'SVLatexView', :path => '../'
  pod 'RxSwift'
  pod 'RxCocoa'
  target 'SVLatexView_Tests' do
    inherit! :search_paths

    
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '5.0'
    end
  end
end
